In [1]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
import sys
import os
from IPython.display import display
import re

### All Biopesticides and their Functional Profiles Concatenated

In [31]:
directory = '/home/anna/Documents/EcoGenoRisk_Paper_Revisions/Biopesticide Function Profiles'

concat_list = []
for file in os.listdir(directory): 
    # biopest_name = "_".join(file.split(".")[:2])
    # biopest_name = biopest_name.replace('_', " ")
    # biopest_name = biopest_name.replace('faa functional profile', " ")
    # print(biopest_name)
    score_df = pd.read_csv(directory + '/' + file, sep=' ')
    score_df["Name_of_Genome"] = score_df["Name_of_Genome"].str.replace('.faa_matches.tsv', " ", regex=False)
    concat_list.append(score_df)

# print(concat_list)
all_biopest = pd.concat(concat_list)
all_biopest

,Name_of_Genome,1.1.1.1,1.1.1.2,1.1.1.3,1.1.1.4,1.1.1.5,1.1.1.6,1.1.1.7,1.1.1.8,1.1.1.9,...,7.6.2.7,7.6.2.8,7.6.2.9,7.6.2.10,7.6.2.11,7.6.2.12,7.6.2.13,7.6.2.14,7.6.2.15,7.6.2.16
0,Gluconobacter_cerinus,1,1,1,0,0,0,0,0,0,...,0,1,0,0,0,1,0,1,1,0
0,Bacillus_velezensis,1,0,1,1,0,1,0,0,0,...,0,0,1,0,0,0,0,1,0,0
0,Kosakonia_cowanii,1,1,0,0,0,0,0,0,0,...,0,1,1,1,1,0,0,1,1,1
0,Matheylorubrum_populi,0,0,1,0,0,0,0,0,0,...,1,1,0,0,1,1,0,1,0,0
0,Bacillus_amyloliquefaciens,1,0,1,1,0,1,0,0,0,...,0,0,1,0,0,0,0,1,0,0
0,Methylorubrum_extorquens,1,0,1,0,0,0,0,0,0,...,1,1,1,0,1,1,1,1,0,0
1,Wolbachia_pipientis,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
0,Bacillus_Subtilis,0,0,1,1,0,0,0,0,0,...,0,0,1,0,1,0,0,1,0,0
0,Bacillus_paralicheniformis,1,0,1,0,0,0,0,0,0,...,0,0,1,0,1,0,0,1,0,0
0,Baccilus_Licheniformis,0,0,1,0,0,0,0,0,0,...,0,0,1,0,1,0,0,1,0,0
0,Wolbachia_pipientis,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0

### All Difference Scores Concatenated

In [11]:
### Loop through the folder
diff_score_directory = '/home/anna/Documents/EcoGenoRisk_Paper_Revisions/BioPesticide_Difference_Scores_per_Biome'
files_sorted = sorted(os.listdir(diff_score_directory))
iterations = 5

for i in range(0, len(files_sorted), iterations):
    batch_files = files_sorted[i:i + iterations]
    results = []
    for file in batch_files:
        file_path = os.path.join(diff_score_directory, file)
        score_df = pd.read_csv(file_path, sep='\t')
        # print(score_df.shape)

        filename = file
        biome_name = re.search(r'And(.*?)_Metagenome', filename)
        if biome_name:
            extracted = biome_name.group(1)
            # print(extracted)
            extracted = extracted.replace('_', " ")
        score_df['Biome'] = extracted
        
        score_df["JGI Bin ID"] = score_df["Organisms Compared to Synbio"].str.replace('_matches.tsv', " ", regex=False)
        score_df = score_df.drop(columns="Organisms Compared to Synbio")
        score_df = score_df.drop(score_df.columns[[0]], axis = 1)
        results.append(score_df)

    bio_name = file.split('.', 1)[0]
    bio_name = bio_name.replace('_', " ")
    print(bio_name)
    chunk_dataframe = pd.concat(results, axis = 0)
    # chunk_dataframe.to_excel('Difference Scores Concatenated' + str(counter) + '.xlsx')
    # counter += 1
    display(chunk_dataframe)
    # print(chunk_dataframe.shape)

### Read in each file 
### Take the top 10 difference scores
### Assign the biome to the difference scores
### Put into a list 
### concatane per synbio org

Baccilus Licheniformis

     Difference Score             Biome       JGI Bin ID
0                 550  Activated Sludge  3300055001_305
1                 552  Activated Sludge  3300056599_149
2                 556  Activated Sludge  3300056788_159
3                 557  Activated Sludge  3300055001_189
4                 557  Activated Sludge  3300057002_117
..                ...               ...              ...
628               826    River Sediment  3300060285_145
629               838    River Sediment  3300060284_119
630               873    River Sediment  3300060285_131
631               912    River Sediment   3300060285_99
632               912    River Sediment   3300060284_21

[7753 rows x 3 columns]

Bacillus Subtilis

     Difference Score             Biome       JGI Bin ID
0                 520  Activated Sludge  3300056623_185
1                 524  Activated Sludge  3300055001_305
2                 525  Activated Sludge  3300056850_284
3                 527  Activated Sludge  3300055001_370
4                 529  Activated Sludge  3300056831_209
..                ...               ...              ...
628               812    River Sediment  3300060285_145
629               822    River Sediment  3300060284_119
630               855    River Sediment  3300060285_131
631               884    River Sediment   3300060285_99
632               888    River Sediment   3300060284_21

[7753 rows x 3 columns]

Bacillus amyloliquefaciens

     Difference Score             Biome       JGI Bin ID
0                 503  Activated Sludge   3300056623_89
1                 503  Activated Sludge  3300056624_336
2                 503  Activated Sludge  3300056625_406
3                 503  Activated Sludge  3300056827_205
4                 504  Activated Sludge  3300056831_209
..                ...               ...              ...
628               797    River Sediment  3300060285_145
629               813    River Sediment  3300060284_119
630               844    River Sediment  3300060285_131
631               863    River Sediment   3300060285_99
632               867    River Sediment   3300060284_21

[7753 rows x 3 columns]

Bacillus paralicheniformis

     Difference Score             Biome       JGI Bin ID
0                 561  Activated Sludge  3300055001_305
1                 568  Activated Sludge  3300057002_107
2                 569  Activated Sludge   3300056831_68
3                 569  Activated Sludge  3300056599_149
4                 570  Activated Sludge  3300057002_117
..                ...               ...              ...
628               829    River Sediment   3300060285_71
629               835    River Sediment  3300060284_119
630               868    River Sediment  3300060285_131
631               913    River Sediment   3300060285_99
632               915    River Sediment   3300060284_21

[7753 rows x 3 columns]

Bacillus velezensis

     Difference Score             Biome       JGI Bin ID
0                 508  Activated Sludge  3300056827_205
1                 508  Activated Sludge  3300056625_406
2                 508  Activated Sludge  3300056624_336
3                 508  Activated Sludge   3300056623_89
4                 509  Activated Sludge  3300056831_209
..                ...               ...              ...
628               800    River Sediment  3300060285_145
629               812    River Sediment  3300060284_119
630               845    River Sediment  3300060285_131
631               866    River Sediment   3300060285_99
632               870    River Sediment   3300060284_21

[7753 rows x 3 columns]

Gluconobacter cerinus

     Difference Score             Biome       JGI Bin ID
0                 400  Activated Sludge   3300056827_37
1                 403  Activated Sludge  3300055001_402
2                 419  Activated Sludge  3300056623_185
3                 424  Activated Sludge   3300057002_49
4                 424  Activated Sludge   3300005657_13
..                ...               ...              ...
628               775    River Sediment  3300060285_119
629               778    River Sediment   3300060281_32
630               782    River Sediment   3300060288_23
631               813    River Sediment  3300060284_119
632               830    River Sediment  3300060285_131

[7753 rows x 3 columns]

Kosakonia cowanii

     Difference Score             Biome       JGI Bin ID
0                 550  Activated Sludge   3300053043_18
1                 567  Activated Sludge  3300055001_311
2                 568  Activated Sludge  3300056850_251
3                 569  Activated Sludge    3300057002_8
4                 571  Activated Sludge   3300009540_46
..                ...               ...              ...
628               878    River Sediment   3300060288_23
629               886    River Sediment   3300060281_32
630               889    River Sediment   3300060285_99
631               891    River Sediment   3300060284_21
632               906    River Sediment  3300060285_131

[7753 rows x 3 columns]

Matheylorubrum populi

     Difference Score             Biome       JGI Bin ID
0                 472  Activated Sludge  3300055001_268
1                 483  Activated Sludge  3300056789_163
2                 486  Activated Sludge  3300055001_402
3                 487  Activated Sludge   3300056827_37
4                 487  Activated Sludge  3300055001_250
..                ...               ...              ...
628               789    River Sediment   3300049473_27
629               794    River Sediment  3300060284_119
630               805    River Sediment    3300036774_2
631               814    River Sediment   3300049473_46
632               821    River Sediment  3300060285_131

[7753 rows x 3 columns]

Methylorubrum extorquens

     Difference Score             Biome       JGI Bin ID
0                 489  Activated Sludge  3300055001_268
1                 500  Activated Sludge  3300056789_163
2                 502  Activated Sludge  3300055001_250
3                 505  Activated Sludge  3300056788_136
4                 505  Activated Sludge  3300055001_402
..                ...               ...              ...
628               811    River Sediment  3300060284_119
629               812    River Sediment   3300049473_27
630               820    River Sediment    3300036774_2
631               829    River Sediment   3300049473_46
632               850    River Sediment  3300060285_131

[7753 rows x 3 columns]

Wolbachia pipientis

     Difference Score             Biome       JGI Bin ID
0                 154  Activated Sludge  3300056827_400
1                 154  Activated Sludge  3300055001_351
2                 158  Activated Sludge  3300056850_218
3                 164  Activated Sludge  3300056825_358
4                 165  Activated Sludge  3300056759_303
..                ...               ...              ...
628               789    River Sediment   3300060285_21
629               790    River Sediment   3300060288_23
630               793    River Sediment   3300060284_21
631               844    River Sediment  3300060285_131
632               863    River Sediment  3300060284_119

[7753 rows x 3 columns]